### ISSUE TITLE
What's the best way to make the app free when it launches in beta?

### ISSUE THREAD

**Issue by Jimmylet** [laravel/cashier-mollie#141]
Hello all,

I'm in the process of integrating Mollie into my future SaaS application.

First, I will launch my application in beta version. This beta version will be free.

Once I consider that my application is bug-free, tested and ready to be sold, I will switch it to a paid version.

Ideally, I would like to do all the payment and subscription logic now.

My question: how do I make the app free now and switch to a paid version later?

How would you do it with Mollie?

Thank you

**Comment by sandervanhooft** [comment]
Hi @Jimmylet,

Good thinking.

There are essentially two way to deal with this with Cashier Mollie:

1. Generic trial. No payment / card required. Most user friendly way and a good way to get people to test functionality.

2. Small payment upfront to get a mandate, optionally add the payment to the user balance. This allows you to switch them to paid plans later on without needing them to go through checkout again. This may result in less users (testers) but will allow you to gauge the business side of things (are people willing to pay for this?).

That's why I personally I like doing 1) for closed group alpha testing and 2) in public testing.

You may find some answers here as well: #122.

Let me know if this helps.

**Comment by Jimmylet** [comment]
Hello @sandervanhooft,

Thanks for your help! I think I will use "Generic trial". It's a good idea.

According to the doc, I have to fill in the column "trial_ends_at". If I add 365 days to registration, for example, will they have access to the full app for 365 days?

When I would like to switch the application to "paid" mode, I would only have to mass edit my SQL database to reset the "trial_end_at" field to NULL. They won't be able to access it anymore, right?

Thank you

**Comment by sandervanhooft** [comment]
Exactly.

You could also set the default trial_ends_at value in the migration file to a date far far away (i.e. 10 years) for the same result.

Another way to end the trials would be to mass update the trial_ends_at to `now()`, forcing the users to switch to a paid subscription.

Anyway, I think you're on the right track now :). Will close this issue, let me know if it should be reopened.
