### ISSUE TITLE
Ecurring, Mollie and Cashier Mollie

### ISSUE THREAD

**Issue by jasperf** [laravel/cashier-mollie#184]
Building a SaaS here selling monthly and yearly subscriptions. Just got my Mollie account and working on Cashier Mollie now. then I bumped into https://docs.ecurring.com/ . A(nother) setup by Mollie that also does recurring payments or subscriptions. 

Do I understand correctly that Cashier Mollie does a more regular Mollie subscriptions approach not using _Ecurring_? 

Two, does Cashier Mollie use direct debit mostly or would you recommend just billing monthly or yearly using regular iDEAL, credit card payments or bank transfers. We thought direct debit / incasso here. So confused at the moment..

**Comment by sandervanhooft** [comment]
Hi @jasperf ,

I get your confusion. Here's my 50cts:

- Mollie offers a basic subscription API (`/subscriptions` endpoint). It's for simple start/stop subscriptions. No invoice pdfs, no plan management, plan swaps, etc. .
- This package offers some advanced subscription logic similar to the cashier stripe edition. It leverages the Mollie API, specifically the `customers`, `payments` and `mandates` endpoints. The benefits are that because all scheduling logic etc. is included in the package, you have a more native Laravel expirience, being able to listen for events etc. .
- eCurring is a daughter company of Mollie, offering recurring payment solutions. eCurring leverages Mollie's API, so you'll be paying for both. I haven't used their services, so I can't comment on their features.

Cashier Mollie allows you to use any recurring payment method offered by Mollie. Your customer will proceed through Mollie's checkout only for the first payment. This results in a mandate which is used to schedule subsequent payments.

**Comment by jasperf** [comment]
@sandervanhooft Thanks a lot for your feedback. Appreciate it a lot.

- We do not want to pay for Mollie and another service like eCurring if we can't help it. So we shall stick with Mollie. 
- We love the way Cashier Mollie builds on Laravel Cashier and Laravel so we can do customer data, payment, mandates (recurring / direct debit permissions). And that Laravel native actions such as listening for events are now possible

**NB** Only downside we have found so far in the world of Payment Service Providers (PSP) and Accounting software is that we need to work with two APIs and that the worlds of developers and accountants still seems to be worlds apart.. Once to make transactions (Mollie PSP) and one to the bookkeeping (Yuki, E-boekhouden, Twinfield, WeFact and so on) to update client details and or render invoices. If you do of a more integrated solution or bookkeeping software that works well with Mollie and has a nice API (Laravel friendly) please do tell.

**Comment by sandervanhooft** [comment]
Moneybird perhaps?

**Comment by jasperf** [comment]
@sandervanhooft Looking into Moneybird and their https://github.com/picqer/moneybird-php-client PHP Client by Picqer. Pretty well maintainted package and Moneybird is pretty moder and has a sandbox for testing of their REST API. Looking interesting. Thanks Sander!

**Comment by sandervanhooft** [comment]
I’m really happy with Moneybird. There is no direct integration with Cashier Mollie, but setting it up for normal cashier payments shouldn’t be hard. Accounting for refunds and chargebacks can be a bit trickier though. Enjoy!
