### ISSUE TITLE
webhook_url and first_payment['webhook_url'] config doesn't work 

### ISSUE THREAD

**Issue by Perafan18** [laravel/cashier-mollie#220]
## Steps to reproduce:
Create a new Laravel project.
Include the package.
Get the API key.
run `php artisan route:list`
Change the value of `webhook_url`.
run `php artisan route:list`

The URL of the webhook doesn't change.

**Comment by jelleroorda** [comment]
Hi Perafan,

If I remember correctly the webhook url in the config is simply an override. This means that if you change this value, your custom webhook url will be passed to Mollie when creating the Mollie payment. Mollie will then call your webhook instead of the default.
Keep in mind that the default webhook route from this Mollie package will stay registered, even if you change the configuration.

This means that this is what you need to do to override the result webhook:
- you register your own route for the custom webhook
- You implement the handling of the webhook yourself (add the controller for the route you registered)
- update the Mollie configuration to point to your newly created route.
- try to create a new subscription to check if it works

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.

**Comment by sandervanhooft** [comment]
Looking into PR #221, I tend to agree with @Perafan18.

**Comment by sandervanhooft** [comment]
Merged into dev. Thanks for your persistence @Perafan18!
