### ISSUE TITLE
What happens if user has two subscriptions of the same name?

### ISSUE THREAD

**Issue by zqstack** [laravel/cashier-mollie#239]
Dear Developer,

In my application I allow users to upgrade to another plan of the same subscription name while they have an existing subscription running. What would happen to the old subscription? Would it be canceled?

It seems like the newest subscription is the active one. Would the other (old) subscription still be charged?

Also: If a user upgrades, would there be a way to discount the remaining days of the old subscription from the first payment of the new subscription?

This is what it looks like in the DB:

**subscriptions table**

id: 17
name: main
plan: pro_monthly
ends_at: NULL
cycle_started_at: 2020-09-03 14:37:10
cycle_ends_at: 2020-10-03 14:37:10

id: 18
name: main
plan: flex_monthly
ends_at: 2020-09-03 15:04:32
cycle_started_at: 2020-09-03 14:49:32
cycle_ends_at: NULL

Thank you very much!

Sincerely,

zqstack

**Comment by zqstack** [comment]
Or should I use swap()? How does it work exactly?

**Comment by zqstack** [comment]
I'm affraid I would be charged after one year (unwantedly) :)

**Comment by zqstack** [comment]
Thank you so much! So I need to use swap() only? It seems that it changes my subscription plan, but I did not receive any payment from either credit card or ideal.

And the double subscription, would the old one still be charged? I removed the previous subscription from the subscriptions table.

**Comment by sandervanhooft** [comment]
> Thank you so much! So I need to use swap() only?
Yes :)

>  When would it be charged?
When executing `cashier::run` the order will be processed. If a payment should be incurred, it will be triggered then. Sometimes the user has enough credit balance or the payment amount is too low for Mollie to accept. Then it will be put on the User's balance.

> And the double subscription, would the old one still be charged? I removed the previous subscription from the subscriptions table.
Instead of modifying the table directly, use `cancelNow()` to cancel subscriptions immediately. Any related scheduled OrderItems will still be processed.

Note that if you're using Mollie's test mode, payments will not automatically reach status `paid`.

**Comment by zqstack** [comment]
Ah, that clarifies a lot!

What happens if the payment fails? For example, there is not enough money available on their account? Would the subscription be canceled?

**Comment by sandervanhooft** [comment]
Yes
