### ISSUE TITLE
Order items for each subscription

### ISSUE THREAD

**Issue by pepijndik** [laravel/cashier-mollie#311]
First of all very **nice package**!

I know i that i can setup my subscriptions in the  config subscriptions file.
But what i am looking for is that i can
Attach custom prices  for each customer see it like a e commerce system.
we have  multiple products and a few are one time payments and others are montly payments. But we dont like to send every month invoices by our self... so i came across this verry nice package.  Is there any option i can attach custom prices for each customer? And attach the order items to the created invoices?
I was also looking to enable/ disable the automatic payments so that admins can create subscriptions for customers but for this i have to wait for v2.0 i saw

Hope some one can help me in the right direction
Kind regards!

**Comment by sandervanhooft** [comment]
I don't think I understand your questions. Can you elaborate on your use case?

**Comment by pepijndik** [comment]
We have an administration panel to create customers and orders for those customers.  Orders have multiple-order items and each order item has unique variables attached to it this is now a basic invoice system.

But because most of our products are monthly based we wanted a way to charge customers automatically. With mollie Sepa incasso. So I came across this magnificent package 👍 .  

But I notice that I have to set the subscriptions in the config file and then attach this subscription to the customer. Is there a way that I can add order items to the subscription and give a specific total price to that subscription. 
I have looked in the OrderitemPreprocessor but have not figured out how it works yet :-)  
Hope this explain the use case a little bit

**Comment by sandervanhooft** [comment]
That definitely helps, thanks!

I think you're on the right track.

- You can use your own repository (i.e. db) for the subscription plans. This is helpful if there are a lot.
- One customer can have multiple active subscriptions.
- I definitely recommend looking into OrderItemPreprocessors for your use case. One thing to be aware of is that these are limited in functionality on first payments, so it may make sense to obtain the customer's payment mandate first. Since you're using SEPA incasso you can create the mandates manually yourself, just make sure to store these on the billable model's table along with the customer id.

**Comment by pepijndik** [comment]
I can't find anywhere how i can create the mandates manually do you have an example? :-) Thanks a lot!

**Comment by sandervanhooft** [comment]
https://docs.mollie.com/reference/v2/mandates-api/create-mandate

Something like this (typing this on my phone, may be flawed):

```php
$customerId = billable->asMollieCustomer()->id;

$mandate = mollie()->mandates->create([...]); // use $customerId, see Mollie docs

$billable->mollie_mandate_id = $mandate->id;
$billable->save();
```

Now you can start the subscription etc..

Make sure to **communicate very clearly** to your customers that you will charge them like this and keep their consent on record.
