### ISSUE TITLE
How does subscription per year per user work?

### ISSUE THREAD

**Issue by Jimmylet** [laravel/cashier-mollie#36]
Hello,

Thank you for this great package.

I ask myself a question about the subscription per user per year.

I will integrate this package for teams. I will create a valid plan 12 months per user. When the administrator adds a user to the team, he will increment the amount.

If I understand correctly, it will only be charged for this additional user at the end of his current period? So, if he has 10 months of subscriptions left and he adds a new seat, this new seat will only be charged 10 months later. A little annoying.

Am I right?

**Comment by sandervanhooft** [comment]
I think I have built it the way you are hoping for, because the issue you're describing would definitely be annoying. 😉

The feature you're looking for is called _prorating_, and Cashier for Mollie does this by default.

When you're updating the quantity (or switching to another plan):

1. the billing cycle is reset
2. the customer is credited for unused time
3. a new billing cycle is started with the new settings. An Order (and payment) is generated to deal with all of the previous, including applying the credited balance to the Order.

Does this answer your question @Jimmylet ?

**Comment by Jimmylet** [comment]
Yes, thank you for your great answer !
