### ISSUE TITLE
Way to go for showing order confirmation/failed page

### ISSUE THREAD

**Issue by marijnbent** [laravel/cashier-mollie#86]
What would be the way to go for showing the correct page after the user returns from Mollie. If the orderId was added to the redirect_url, we could fetch the mollie_payment_status. What's your take on this @sandervanhooft?

**Comment by sandervanhooft** [comment]
At first glance I kinda like it :). Would save me some trouble with Spark as well if we can solve this in Cashier.

**Comment by sandervanhooft** [comment]
We could use `{order_id}` in the route, and replace it dynamically if it's used there.

**Comment by sandervanhooft** [comment]
Scratch that. The Order is not created before the payment has been paid, so there's no `order_id` available. 

I have discussed this with Mollie a while ago, and we ended up adding an Update Payment API endpoint.

Long story short: we can update the Payment's `redirectUrl` right after the payment has been created in order to include the `paymentId` (i.e. when the `redirectUrl` contains `{payment_id}`) , and use that for checking the status.

**Comment by sandervanhooft** [comment]
So that would all need to happen in the `FirstPaymentBuilder.create()` method.

**Comment by sandervanhooft** [comment]
Fix merged in `develop` 😄 .

With this you will be able to use `{payment_id}` in the `redirectUrl`. Using this `payment_id` in your controller, you can either retrieve the Order (locally) or the Payment (from Mollie) to check the status.

```php

$paymentId = $request->get('payment_id');
$order = Order::whereMolliePaymentId($paymentId)->findOrFail();
$order->mollie_payment_status; // depending on Mollie / your app, this may take a second

$payment = mollie()->payments->get($paymentId);
$payment->status; // Always up to date
```

Make sure you reference the `{payment_id}` in your route definition as well!

**Comment by sandervanhooft** [comment]
I don't know about you @marijnbent , but I am really happy about this 🕺 !

**Comment by marijnbent** [comment]
Really cool Sander! This should help a lot with displaying the proper page, thanks 💃!
