### ISSUE TITLE
Simplify coupon validation

### ISSUE THREAD

**Issue by sandervanhooft** [laravel/cashier-mollie#90]
Hi everyone,

For the Spark integration it would be beneficial to simplify the Coupon validation.

The current Coupon method signature for validation is:

```php
public function validateFor(AcceptsCoupons $model)
```

I built this to enable a stricter checking of the coupon than simply checking it for existence. But now it's released I notice that it's overly complex for many use cases to prepare a (unpersisted) `$model` that would be accepting the discount and pass it to the `validateFor` method.

Specifically while integrating Cashier Mollie into Spark I noticed that in Spark a simpler method signature is used ([CouponRepository](https://github.com/laravel/spark-aurelius/blob/9.0/src/Repositories/StripeCouponRepository.php#L16:L19
)):

```php
public function valid($code)
```

So the question here is:

**Would it be feasible to simplify the Coupon validation (i.e. in Cashier Mollie v2)?**

(Pinging @RobertBoes , as I know you have already been tinkering with Cashier's Coupon functionality 😄 )

**Comment by RobertBoes** [comment]
So the check would change from "exists and not used before" to "exists"?

I don't see a reason to change the validation, since there could be a lot other requirements in certain projects. For example I could imagine a coupon to only be applicable to one plan, which requires me to handle this in my project, that doesn't have to be a task of cashier to check. The applied-before check is also quite opinionated, while the check in Spark is only to check if the coupon code exists.

**Comment by sandervanhooft** [comment]
Thanks for weighing in @RobertBoes .

The validation you are referring to is the one I've included by default, and I think it will match most (basic) use cases. I'm happy it matches your expectations (as it did mine).

The primary reason I am doing this sanity check here is that it will require some hacking into Spark to get this to work. 😅 

But I agree, I've designed the validation like this for a reason and the reasoning behind it still stands.

Thanks.
